const jobs=[
{id:"JOB-0187",name:"John Smith",phone:"+18315550101",time:"10:00 AM",type:"Treadmill Delivery",address:"123 Main St, Soquel",status:"Scheduled",action:"Call"},
{id:"JOB-0188",name:"Sarah Johnson",phone:"+18315550102",time:"11:00 AM",type:"Pickup",address:"456 Ocean St, Santa Cruz",status:"Scheduled",action:"Call"},
{id:"JOB-0189",name:"Mike Davis",phone:"+18315550103",time:"Tomorrow, 9:00 AM",type:"Delivery · 2 Items",address:"789 Bay Ave, Capitola",status:"Tentative",action:"Review"},
{id:"JOB-0190",name:"Emily Davis",phone:"+18315550104",time:"1:30 PM",type:"Home Gym Package",address:"321 Lighthouse Ave, Santa Cruz",status:"Scheduled",action:"Open"}];
const customers=[
{name:"John Smith",phone:"(831) 555-0101",email:"john@example.com",jobs:3},
{name:"Sarah Johnson",phone:"(831) 555-0102",email:"sarah@example.com",jobs:1},
{name:"Mike Davis",phone:"(831) 555-0103",email:"mike@example.com",jobs:2}];
const todayDate=new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date());
const q=j=>`<article><div class="icon">${j.action==="Call"?"☎":j.action==="Review"?"▣":"◇"}</div><div><h3>${j.action==="Call"?"Call ":""}${j.name}</h3><p>${j.time} · ${j.type}<br>${j.address}</p><span class="badge ${j.status.toLowerCase()}">${j.status}</span></div>${j.action==="Call"?`<a class="button" href="tel:${j.phone}">Call</a>`:`<button class="button demo-action">${j.action}</button>`}</article>`;
const views={
today:{title:"Today's GamePlan",sub:todayDate,html:()=>`<div class="grid two"><div class="grid"><section class="alert"><b>🔧</b><div class="copy"><strong>Build Alerts</strong><span>2 deliveries in the next 48 hours still need equipment assembled.</span></div><button class="button demo-action">View Items</button></section><section class="card"><div class="head"><h2>Today's Queue</h2></div><div class="body queue">${jobs.map(q).join("")}</div></section></div><div class="grid"><section class="card"><div class="head"><h2>Quick Actions</h2></div><div class="body quick"><button class="demo-action">＋<br>New Job</button><button data-route="roster">◎<br>Find Customer</button><button data-route="schedule">▣<br>Schedule</button></div></section><section class="card"><div class="head"><h2>Today</h2></div><div class="body stats"><div class="stat"><b>3</b><span>Deliveries</span></div><div class="stat"><b>1</b><span>Pickup</span></div><div class="stat"><b>1</b><span>Tentative</span></div><div class="stat"><b>0</b><span>Conflicts</span></div></div></section></div></div>`},
schedule:{title:"Schedule",sub:"Internal GamePlan schedule",html:()=>`<section class="card"><div class="head"><h2>Upcoming Jobs</h2><button class="button demo-action">New Tentative</button></div><div class="body list">${jobs.map(j=>`<div class="row"><div><b>${j.time} · ${j.name}</b><span>${j.type} · ${j.address}</span></div><span class="badge ${j.status.toLowerCase()}">${j.status}</span></div>`).join("")}</div></section>`},
jobs:{title:"Jobs",sub:"Quotes, tentative appointments, scheduled work, and history",html:()=>`<section class="card"><div class="head"><h2>All Jobs</h2><button class="button demo-action">New Job</button></div><div class="body list">${jobs.map(j=>`<div class="row"><div><b>${j.name}</b><span>${j.id} · ${j.type} · ${j.time}</span></div><span class="badge ${j.status.toLowerCase()}">${j.status}</span></div>`).join("")}</div></section>`},
roster:{title:"Roster",sub:"Customers and saved service addresses",html:()=>`<section class="card"><div class="head"><h2>Customers</h2><button class="button demo-action">Add Customer</button></div><div class="body list">${customers.map(c=>`<div class="row"><div><b>${c.name}</b><span>${c.phone} · ${c.email}</span></div><span class="badge">${c.jobs} jobs</span></div>`).join("")}</div></section>`},
more:{title:"More",sub:"Administration and app information",html:()=>`<div class="grid two"><section class="card"><div class="head"><h2>Administration</h2></div><div class="body list"><button class="row demo-action"><div><b>Settings</b><span>Pricing, timing, availability, and app rules</span></div><b>⚙</b></button><button class="row demo-action"><div><b>Huddle Together</b><span>Group scheduled jobs into one operational route</span></div><b>↝</b></button></div></section><section class="card"><div class="head"><h2>System</h2></div><div class="body"><div class="row"><div><b>Environment</b><span>Milestone 1 demo mode</span></div><span class="badge tentative">Demo</span></div></div></section></div>`}
};
const view=document.querySelector("#view"),title=document.querySelector("#title"),sub=document.querySelector("#subtitle"),toastBox=document.querySelector("#toast");
function toast(t){toastBox.innerHTML=`<div class="toast">${t}</div>`;setTimeout(()=>toastBox.innerHTML="",2600)}
function go(r){const v=views[r]||views.today;title.textContent=v.title;sub.textContent=v.sub;view.innerHTML=v.html();document.querySelectorAll("[data-route]").forEach(b=>b.classList.toggle("active",b.dataset.route===r));view.querySelectorAll(".demo-action").forEach(b=>b.onclick=()=>toast(`${b.textContent.trim()} becomes active in the next milestone.`));view.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>go(b.dataset.route));history.replaceState({}, "", `#${r}`)}
document.addEventListener("click",e=>{const b=e.target.closest("[data-route]");if(b&&!b.closest("#view"))go(b.dataset.route)});
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(console.error));
window.addEventListener("offline",()=>toast("Offline — showing cached app shell."));
window.addEventListener("online",()=>toast("Connection restored."));
go(location.hash.slice(1)||"today");